apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    MatchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-containers
        image: utkarshsrivastava9294/myapp
        ports:
        - containerPort: 5000
        