apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: flask-app-mysql
spec:
  containers:
  - name: mysql-containers
    image: utkarshsrivastava9294/mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: flask-app-secret
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: flask-app-secret
          key: MYSQL_DATABASE 
