apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secret
stringData:
  DB_HOST: mysql-svc
  DB_USER: root
  DB_PASSWORD: root
  DB_NAME: testdb
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: testdb